-- Continue even if some objects do not exist yet.
--#SET TERMINATOR @

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TRIGGER TRG_TICKET_PRICE_AUDIT';
END
@

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP TABLE Ticket_Price_Audit';
END
@

BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
	EXECUTE IMMEDIATE 'DROP VARIABLE CURRENT_EMPLOYEE_ID';
END
@

--#SET TERMINATOR ;

DROP TABLE Fan;
DROP TABLE Venue;
DROP TABLE Management;
DROP TABLE Artist;
DROP TABLE Tour_Event;
DROP TABLE Concert;
DROP TABLE Fansign;
DROP TABLE Listing;
DROP TABLE Likes;
DROP TABLE Employee;
DROP TABLE Ticket;
DROP TABLE Buys_Ticket;
